//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KREAM_ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoteles
    {
        public int IDHotel { get; set; }
        public string TipoDeHabitacion { get; set; }
        public Nullable<int> CantidadDePersonas { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string NombreHotel { get; set; }
        public byte[] Imagen { get; set; }
        public byte[] Imagen2 { get; set; }
        public byte[] Imagen3 { get; set; }
        public string web { get; set; }
        public string ComentarioHotel { get; set; }
        public Nullable<int> CalificacionHotel { get; set; }
    }
}
